"""Realistic Nightscout emulator -- emulates a Loop user.

Drives the local test Nightscout instance with continuously-arriving
data shaped like a real Loop / iAPS user's day:

- CGM entries every 5 simulated minutes (300s of simulated time).
- Loop-shaped devicestatus on every entry tick (loop subtree with
  iob, cob, predicted glucose, recommendation, enacted basal).
- Treatments (Meal Bolus, Correction Bolus) generated by a
  physiology state machine, not random noise -- carbs raise BG over
  ~90 min, insulin lowers it across DIA, dawn phenomenon kicks at
  4-7 am, all clamped to 40-400 mg/dL.
- A profile snapshot posted on first run if none exists.

Why this exists: the simpler `ns_synthetic_uploader.py` random-walks
SGV values and is fine for "does data flow" smoke tests, but doesn't
exercise the closed-loop signal paths (loop_subtree_json,
predictive BG, COB) or produce data that visually resembles a real
patient on the dashboard. This script does.

Time compression: by default each wall-clock 30 seconds emits one
"5-minute" reading -- so a full simulated day lands in ~24 minutes.
Set `NS_TIME_COMPRESSION=1` for realtime (5-min cadence; useful only
for long-running derisks).

NOT shipped in any production image. Stdlib-only by design (no
httpx / requests) so it runs anywhere a Python 3.11+ interpreter is
available.

Usage:
    NS_API_SECRET="<your-test-stack-secret>" \\
      python3 dev/ns_realistic_emulator.py

Env vars:
    NS_BASE_URL          default http://127.0.0.1:1337
    NS_API_SECRET        REQUIRED. Plaintext API_SECRET.
    NS_TIME_COMPRESSION  default 10 (30s wall = 5min sim). Set 1 for
                          realtime; 60 for fast-fwd "an hour every minute".
    NS_DURATION_HOURS    default 24 (simulated). Loop terminates after
                          this many simulated hours. Set 0 for unbounded.
    NS_DEVICE_NAME       default "loop://iPhone/realistic-emulator"
    NS_RANDOM_SEED       default unset (truly random). Set to an int
                          for reproducible runs.
    NS_STARTING_BG       default 120. Initial blood-glucose value.
    NS_PROFILE_NAME      default "Default" -- the profile we post.

Stops on Ctrl-C. No state persistence -- restart fresh.
"""

from __future__ import annotations

import datetime
import hashlib
import json
import math
import os
import random
import signal
import socket
import sys
import time
import urllib.error
import urllib.request

# ---------------------------------------------------------------------------
# Profile (the "user's" insulin / carb model)
# ---------------------------------------------------------------------------

# 1 unit of insulin lowers BG by this much (realistic adult range
# is 30-70 mg/dL/U; pick a moderate value).
ISF_MGDL_PER_UNIT = 50.0

# 1 unit of insulin covers this many grams of carbs.
ICR_GRAMS_PER_UNIT = 10.0

# Total duration of insulin action in minutes -- after this long,
# a bolus has fully cleared.
DIA_MINUTES = 240

# Carb absorption window. After this long, all of a meal's COB has
# been absorbed.
CARB_ABSORPTION_MINUTES = 90

# Pump basal rate in U/hr (steady state, assumed to offset
# endogenous glucose production -- doesn't appear in the BG-delta
# math directly, but it does appear in devicestatus).
BASAL_U_PER_HR = 0.8

# Target glucose -- written to profile, used by the correction
# heuristic.
TARGET_BG_MGDL = 110.0

# Minimum / maximum glucose values to clamp the model output to.
BG_FLOOR = 40
BG_CEIL = 400

# Probability that a meal happens during a given 5-min tick when
# the simulated clock is inside a meal window.
MEAL_TICK_PROBABILITY = 0.18

# (Hour-of-day-start, end) windows that are "meal time."
MEAL_WINDOWS = [
    (7, 9),  # breakfast
    (12, 13),  # lunch
    (18, 20),  # dinner
]

# Snack between meals: smaller carb amount, lower probability.
SNACK_TICK_PROBABILITY = 0.04
SNACK_WINDOWS = [(10, 11), (15, 16)]

# Correction trigger: BG above this AND IoB below this many units
# AND time since last correction at least this many minutes.
CORRECTION_BG_THRESHOLD = 200
CORRECTION_IOB_CEILING = 1.5
CORRECTION_COOLDOWN_MIN = 90

# Dawn-phenomenon bias (added to BG delta during the early-morning
# hours; tapers off by 7am).
DAWN_START_HOUR = 4
DAWN_END_HOUR = 7
DAWN_PEAK_DELTA_PER_HOUR = 8.0  # mg/dL/hr at the strongest


# ---------------------------------------------------------------------------
# Insulin / carb activity curves
# ---------------------------------------------------------------------------


class _Bolus:
    """A single bolus delivery, tracked until DIA elapses.

    Linear-decay model: at t=0 the full units are 'on board', at
    t=DIA all units have cleared. Real insulin curves are
    bi-exponential with a peak around 60-90 min, but linear is good
    enough for the "what BG curve does the dashboard render" use
    case and dramatically simpler to reason about.
    """

    __slots__ = ("units", "delivered_at_min")

    def __init__(self, units: float, delivered_at_min: float):
        self.units = units
        self.delivered_at_min = delivered_at_min

    def remaining_at(self, sim_minute: float) -> float:
        elapsed = sim_minute - self.delivered_at_min
        if elapsed <= 0:
            return self.units
        if elapsed >= DIA_MINUTES:
            return 0.0
        return self.units * (1.0 - elapsed / DIA_MINUTES)

    def cleared_in_interval(self, prev_min: float, curr_min: float) -> float:
        """Units that finished decaying between prev_min and curr_min.

        Determines how much insulin actually acted on BG during this
        5-min slice.
        """
        return self.remaining_at(prev_min) - self.remaining_at(curr_min)


class _CarbEvent:
    """A single meal's carbs, tracked until absorption is complete.

    Linear absorption: at t=0 all carbs are pending, at
    t=CARB_ABSORPTION_MINUTES all have been absorbed.
    """

    __slots__ = ("grams", "ingested_at_min")

    def __init__(self, grams: float, ingested_at_min: float):
        self.grams = grams
        self.ingested_at_min = ingested_at_min

    def cob_at(self, sim_minute: float) -> float:
        elapsed = sim_minute - self.ingested_at_min
        if elapsed <= 0:
            return self.grams
        if elapsed >= CARB_ABSORPTION_MINUTES:
            return 0.0
        return self.grams * (1.0 - elapsed / CARB_ABSORPTION_MINUTES)

    def absorbed_in_interval(self, prev_min: float, curr_min: float) -> float:
        return self.cob_at(prev_min) - self.cob_at(curr_min)


# ---------------------------------------------------------------------------
# Patient state machine
# ---------------------------------------------------------------------------


class PatientState:
    """The simulated patient's physiological state.

    Advances in 5-minute simulated ticks. Holds active boluses,
    active carb events, current BG, and the simulated wall clock.
    """

    def __init__(
        self,
        starting_bg: float,
        starting_sim_time: datetime.datetime,
    ):
        self.bg = float(starting_bg)
        self.sim_time = starting_sim_time
        self.sim_minute = 0.0  # cumulative simulated minutes since start
        self.boluses: list[_Bolus] = []
        self.carb_events: list[_CarbEvent] = []
        self.last_correction_min: float = -math.inf
        # Track which meal/snack windows we've already eaten in, keyed
        # by (date_iso, kind, window_index), so we don't fire 4 dinners
        # in a single 18:00-20:00 window when the dice happen to land.
        self._consumed_windows: set[tuple[str, str, int]] = set()

    @property
    def iob(self) -> float:
        return sum(b.remaining_at(self.sim_minute) for b in self.boluses)

    @property
    def cob(self) -> float:
        return sum(c.cob_at(self.sim_minute) for c in self.carb_events)

    def deliver_bolus(self, units: float) -> None:
        if units <= 0:
            return
        self.boluses.append(_Bolus(units, self.sim_minute))

    def consume_carbs(self, grams: float) -> None:
        if grams <= 0:
            return
        self.carb_events.append(_CarbEvent(grams, self.sim_minute))

    def advance_5_min(self) -> None:
        """Advance 5 simulated minutes; update BG accordingly."""
        prev_min = self.sim_minute
        new_min = prev_min + 5.0

        # Insulin effect: total units cleared in this slice times
        # ISF, working downward on BG.
        insulin_units_cleared = sum(
            b.cleared_in_interval(prev_min, new_min) for b in self.boluses
        )
        insulin_delta = -insulin_units_cleared * ISF_MGDL_PER_UNIT

        # Carb effect: 1g carb without insulin raises BG by ISF/ICR.
        carb_grams_absorbed = sum(
            c.absorbed_in_interval(prev_min, new_min) for c in self.carb_events
        )
        carb_delta = carb_grams_absorbed * (ISF_MGDL_PER_UNIT / ICR_GRAMS_PER_UNIT)

        # Dawn phenomenon: bias upward 4-7 am.
        next_sim = self.sim_time + datetime.timedelta(minutes=5)
        dawn_delta = 0.0
        hour_frac = next_sim.hour + next_sim.minute / 60.0
        if DAWN_START_HOUR <= hour_frac <= DAWN_END_HOUR:
            # Peak in the middle of the window, taper at edges.
            window_pos = (hour_frac - DAWN_START_HOUR) / (
                DAWN_END_HOUR - DAWN_START_HOUR
            )
            envelope = math.sin(window_pos * math.pi)
            dawn_delta = envelope * DAWN_PEAK_DELTA_PER_HOUR * (5 / 60)

        # Noise: small jitter so the chart doesn't look mechanical.
        noise = random.gauss(0, 1.5)

        self.bg = max(
            BG_FLOOR,
            min(BG_CEIL, self.bg + insulin_delta + carb_delta + dawn_delta + noise),
        )
        self.sim_minute = new_min
        self.sim_time = next_sim

        # Garbage-collect fully-decayed boluses / carbs to keep the
        # lists bounded over a multi-day run.
        self.boluses = [
            b for b in self.boluses if b.remaining_at(self.sim_minute) > 1e-6
        ]
        self.carb_events = [
            c for c in self.carb_events if c.cob_at(self.sim_minute) > 1e-6
        ]

    def maybe_meal(self) -> tuple[float, float] | None:
        """Decide if a meal happens this tick. Returns (carbs, bolus).

        At most one meal per (kind, window, day): once dinner has
        fired today, no further dinners can fire in the same 18-20
        window today even if the dice keep coming up under the
        threshold.
        """
        hour = self.sim_time.hour
        date_iso = self.sim_time.date().isoformat()

        meal_window = next(
            ((i, w) for i, w in enumerate(MEAL_WINDOWS) if w[0] <= hour < w[1]),
            None,
        )
        snack_window = next(
            ((i, w) for i, w in enumerate(SNACK_WINDOWS) if w[0] <= hour < w[1]),
            None,
        )

        if meal_window is not None:
            idx, _ = meal_window
            key = (date_iso, "meal", idx)
            if key in self._consumed_windows:
                return None
            if random.random() < MEAL_TICK_PROBABILITY:
                self._consumed_windows.add(key)
                carbs = random.uniform(40, 75)
                return carbs, round(carbs / ICR_GRAMS_PER_UNIT, 2)
            return None

        if snack_window is not None:
            idx, _ = snack_window
            key = (date_iso, "snack", idx)
            if key in self._consumed_windows:
                return None
            if random.random() < SNACK_TICK_PROBABILITY:
                self._consumed_windows.add(key)
                carbs = random.uniform(15, 30)
                return carbs, round(carbs / ICR_GRAMS_PER_UNIT, 2)
            return None

        return None

    def maybe_correction(self) -> float | None:
        if self.bg <= CORRECTION_BG_THRESHOLD:
            return None
        if self.iob >= CORRECTION_IOB_CEILING:
            return None
        if self.sim_minute - self.last_correction_min < CORRECTION_COOLDOWN_MIN:
            return None
        # Standard correction formula: (current - target) / ISF
        units = round((self.bg - TARGET_BG_MGDL) / ISF_MGDL_PER_UNIT, 2)
        if units < 0.1:
            return None
        return units


# ---------------------------------------------------------------------------
# Nightscout posters (entries / treatments / devicestatus / profile)
# ---------------------------------------------------------------------------


def _hash_secret(secret: str) -> str:
    return hashlib.sha1(secret.encode("utf-8")).hexdigest()


def _iso_z(t: datetime.datetime) -> str:
    """ISO-8601 with Z suffix, milliseconds -- the format Nightscout's
    own serializer uses on entries."""
    return t.isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _post(base_url: str, path: str, secret_hash: str, payload) -> None:
    """POST JSON; raise HTTPError on non-2xx (urlopen does that for us)."""
    req = urllib.request.Request(
        f"{base_url.rstrip('/')}{path}",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "api-secret": secret_hash,
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=15):
        pass


def _get(base_url: str, path: str, secret_hash: str):
    req = urllib.request.Request(
        f"{base_url.rstrip('/')}{path}",
        headers={"api-secret": secret_hash},
        method="GET",
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _direction_for(prev: float, curr: float) -> str:
    """Map per-tick BG delta to Dexcom's direction vocabulary."""
    delta = curr - prev
    if delta >= 15:
        return "DoubleUp"
    if delta >= 7:
        return "SingleUp"
    if delta >= 3:
        return "FortyFiveUp"
    if delta <= -15:
        return "DoubleDown"
    if delta <= -7:
        return "SingleDown"
    if delta <= -3:
        return "FortyFiveDown"
    return "Flat"


def _post_entry(
    base_url: str,
    secret_hash: str,
    state: PatientState,
    prev_bg: float,
    device: str,
) -> None:
    payload = [
        {
            "type": "sgv",
            "sgv": int(round(state.bg)),
            "direction": _direction_for(prev_bg, state.bg),
            "date": int(state.sim_time.timestamp() * 1000),
            "dateString": _iso_z(state.sim_time),
            "device": device,
        }
    ]
    _post(base_url, "/api/v1/entries.json", secret_hash, payload)


def _post_meal(
    base_url: str,
    secret_hash: str,
    state: PatientState,
    carbs: float,
    bolus: float,
    device: str,
) -> None:
    """Loop's "Meal Bolus" treatment carries both carbs and insulin
    on a single record."""
    payload = [
        {
            "eventType": "Meal Bolus",
            "created_at": _iso_z(state.sim_time),
            "carbs": round(carbs, 1),
            "insulin": bolus,
            "absorptionTime": int(CARB_ABSORPTION_MINUTES * 60),  # Loop = seconds
            "enteredBy": "loop://realistic-emulator",
            "_id": f"emu-meal-{int(state.sim_time.timestamp())}",
        }
    ]
    _post(base_url, "/api/v1/treatments.json", secret_hash, payload)


def _post_correction(
    base_url: str,
    secret_hash: str,
    state: PatientState,
    units: float,
) -> None:
    payload = [
        {
            "eventType": "Correction Bolus",
            "created_at": _iso_z(state.sim_time),
            "insulin": units,
            "enteredBy": "loop://realistic-emulator",
            "_id": f"emu-corr-{int(state.sim_time.timestamp())}",
        }
    ]
    _post(base_url, "/api/v1/treatments.json", secret_hash, payload)


def _build_devicestatus(
    state: PatientState,
    device: str,
) -> dict:
    """A Loop-shaped devicestatus payload.

    Mirrors what real Loop posts: `loop` subtree with iob/cob,
    a 6-hour `predicted` BG curve, the most recent enacted basal,
    and pump status. Enough for the dashboard's planned closed-loop
    UI surfaces (Story 43.12) to read.
    """
    # Project BG forward up to 6 hours using the same physiology
    # used by the live state machine: insulin still on board lowers
    # BG as it decays; carbs still on board raise it as they absorb.
    # Once both have cleared and we're near target, terminate the
    # curve early -- real Loop trims its predicted curve similarly.
    predicted: list[int] = [int(round(state.bg))]
    proj_bg = state.bg
    for step in range(1, 73):  # 6h * 12 (5-min steps)
        prev_future_min = state.sim_minute + 5 * (step - 1)
        future_min = state.sim_minute + 5 * step
        insulin_cleared = sum(
            b.cleared_in_interval(prev_future_min, future_min) for b in state.boluses
        )
        carbs_absorbed = sum(
            c.absorbed_in_interval(prev_future_min, future_min)
            for c in state.carb_events
        )
        delta = -insulin_cleared * ISF_MGDL_PER_UNIT + carbs_absorbed * (
            ISF_MGDL_PER_UNIT / ICR_GRAMS_PER_UNIT
        )
        # Mild drift toward target so a stable BG with no active
        # insulin / carbs converges instead of holding flat forever.
        delta += (TARGET_BG_MGDL - proj_bg) * 0.02
        proj_bg = max(BG_FLOOR, min(BG_CEIL, proj_bg + delta))
        predicted.append(int(round(proj_bg)))
        future_iob = sum(b.remaining_at(future_min) for b in state.boluses)
        future_cob = sum(c.cob_at(future_min) for c in state.carb_events)
        if (
            future_iob < 1e-3
            and future_cob < 1e-3
            and abs(proj_bg - TARGET_BG_MGDL) < 5
        ):
            break

    now = state.sim_time

    return {
        "device": device,
        "created_at": _iso_z(now),
        "loop": {
            "version": "Loop 3.4.5 (realistic-emulator)",
            "iob": {
                "timestamp": _iso_z(now),
                "iob": round(state.iob, 3),
            },
            "cob": {
                "timestamp": _iso_z(now),
                "cob": round(state.cob, 1),
            },
            "predicted": {
                "startDate": _iso_z(now),
                "values": predicted,
            },
            "recommendedBolus": 0.0,
            "enacted": {
                "timestamp": _iso_z(now),
                "rate": BASAL_U_PER_HR,
                "duration": 30,
                "received": True,
            },
        },
        "pump": {
            "manufacturer": "Insulet",
            "model": "Eros",
            "reservoir": 145.5,
            "battery": {"percent": 80},
        },
    }


def _post_devicestatus(
    base_url: str,
    secret_hash: str,
    state: PatientState,
    device: str,
) -> None:
    _post(
        base_url,
        "/api/v1/devicestatus.json",
        secret_hash,
        [_build_devicestatus(state, device)],
    )


def _ensure_profile(
    base_url: str,
    secret_hash: str,
    profile_name: str,
) -> None:
    """Post a profile if none exists.

    Real Loop / iAPS push a complex profile snapshot. This minimal
    one is enough to populate `nightscout_profile_snapshots` and
    let Story 43.7 onboarding pre-fill defaults.
    """
    try:
        existing = _get(base_url, "/api/v1/profile.json", secret_hash)
        if existing:
            return  # Already has a profile -- don't overwrite.
    except urllib.error.HTTPError:
        pass  # 404 / etc -- proceed to create.

    now_iso = _iso_z(datetime.datetime.now(datetime.UTC))
    payload = {
        "defaultProfile": profile_name,
        "store": {
            profile_name: {
                "dia": str(DIA_MINUTES // 60),
                "carbratio": [{"time": "00:00", "value": ICR_GRAMS_PER_UNIT}],
                "sens": [{"time": "00:00", "value": ISF_MGDL_PER_UNIT}],
                "basal": [{"time": "00:00", "value": BASAL_U_PER_HR}],
                "target_low": [{"time": "00:00", "value": TARGET_BG_MGDL - 10}],
                "target_high": [{"time": "00:00", "value": TARGET_BG_MGDL + 10}],
                "carbs_hr": "20",
                "delay": "20",
                "timezone": "UTC",
                "units": "mg/dl",
            }
        },
        "startDate": now_iso,
        "mills": str(int(time.time() * 1000)),
        "units": "mg/dl",
    }
    # NS v1 /profile.json accepts an array of profile documents
    # (it is effectively a Mongo-collection insert), even when
    # posting a single one. Other endpoints in this file follow the
    # same convention.
    _post(base_url, "/api/v1/profile.json", secret_hash, [payload])


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------


def main() -> int:
    base_url = os.environ.get("NS_BASE_URL", "http://127.0.0.1:1337")
    secret = os.environ.get("NS_API_SECRET")
    if not secret:
        print(
            "ERROR: NS_API_SECRET environment variable is required.\n"
            "Set it to the plaintext API_SECRET of your target "
            "Nightscout instance.",
            file=sys.stderr,
        )
        return 2
    compression = float(os.environ.get("NS_TIME_COMPRESSION", "10"))
    if compression <= 0:
        print("ERROR: NS_TIME_COMPRESSION must be > 0", file=sys.stderr)
        return 2
    duration_hours = float(os.environ.get("NS_DURATION_HOURS", "24"))
    device = os.environ.get("NS_DEVICE_NAME", "loop://iPhone/realistic-emulator")
    starting_bg = float(os.environ.get("NS_STARTING_BG", "120"))
    profile_name = os.environ.get("NS_PROFILE_NAME", "Default")
    seed_env = os.environ.get("NS_RANDOM_SEED")
    if seed_env is not None:
        try:
            random.seed(int(seed_env))
        except ValueError:
            print(
                f"ERROR: NS_RANDOM_SEED must be an int (got {seed_env!r})",
                file=sys.stderr,
            )
            return 2

    # Wall-clock seconds per simulated 5-minute tick:
    #   compression=1   -> 300s wall  (realtime, 5-min cadence)
    #   compression=10  -> 30s  wall  (one simulated day in ~24 min)
    #   compression=60  -> 5s   wall  (one simulated day in 4 min)
    wall_seconds_per_tick = 300.0 / compression

    secret_hash = _hash_secret(secret)
    print(
        f"[emu] target {base_url}; compression {compression}x "
        f"(wall {wall_seconds_per_tick:.1f}s/tick); "
        f"duration {duration_hours}h sim",
        flush=True,
    )

    try:
        _ensure_profile(base_url, secret_hash, profile_name)
        print(f"[emu] profile ensured (default={profile_name})", flush=True)
    except urllib.error.HTTPError as exc:
        if exc.code in (401, 403):
            print(
                f"[emu] FATAL: HTTP {exc.code} {exc.reason} on profile -- "
                "check NS_API_SECRET. Aborting.",
                file=sys.stderr,
            )
            return 1
        print(
            f"[emu] WARN: profile ensure HTTP {exc.code} {exc.reason} -- "
            "continuing without profile.",
            flush=True,
        )
    except urllib.error.URLError as exc:
        if isinstance(exc.reason, socket.gaierror):
            print(
                f"[emu] FATAL: cannot resolve {base_url!r} ({exc.reason}). Aborting.",
                file=sys.stderr,
            )
            return 1
        print(f"[emu] WARN: profile ensure {exc.reason} -- continuing.", flush=True)

    # Anchor sim time to "now" so the dashboard's recent-window views
    # see the data. Forward-only: we never emit timestamps in the past.
    state = PatientState(
        starting_bg=starting_bg,
        starting_sim_time=datetime.datetime.now(datetime.UTC),
    )

    stopping = False

    def _on_signal(signum, _frame):  # type: ignore[no-untyped-def]
        nonlocal stopping
        print(f"\n[emu] caught signal {signum}, stopping", flush=True)
        stopping = True

    signal.signal(signal.SIGINT, _on_signal)
    signal.signal(signal.SIGTERM, _on_signal)

    sim_minutes_max = duration_hours * 60.0 if duration_hours > 0 else math.inf
    last_log_at = time.monotonic()

    while not stopping and state.sim_minute < sim_minutes_max:
        prev_bg = state.bg
        # Decide on meals / corrections BEFORE advancing -- so the
        # newly-added boluses / carbs affect THIS tick's BG move.
        meal = state.maybe_meal()
        if meal is not None:
            carbs_g, bolus_u = meal
            state.consume_carbs(carbs_g)
            state.deliver_bolus(bolus_u)
            try:
                _post_meal(base_url, secret_hash, state, carbs_g, bolus_u, device)
            except (urllib.error.HTTPError, urllib.error.URLError) as exc:
                print(f"[emu] meal post failed: {exc}", flush=True)
        else:
            corr = state.maybe_correction()
            if corr is not None:
                state.deliver_bolus(corr)
                state.last_correction_min = state.sim_minute
                try:
                    _post_correction(base_url, secret_hash, state, corr)
                except (urllib.error.HTTPError, urllib.error.URLError) as exc:
                    print(f"[emu] correction post failed: {exc}", flush=True)

        state.advance_5_min()

        try:
            _post_entry(base_url, secret_hash, state, prev_bg, device)
            _post_devicestatus(base_url, secret_hash, state, device)
        except (urllib.error.HTTPError, urllib.error.URLError) as exc:
            print(f"[emu] entry/devicestatus post failed: {exc}", flush=True)
        except Exception as exc:  # noqa: BLE001 - keep loop running
            print(f"[emu] unexpected error: {exc}", flush=True)

        # Periodic status line, not on every tick.
        now = time.monotonic()
        if now - last_log_at >= 30.0:
            last_log_at = now
            print(
                f"[emu] sim={state.sim_time.isoformat(timespec='seconds')} "
                f"bg={state.bg:.0f} iob={state.iob:.2f} cob={state.cob:.1f} "
                f"boluses={len(state.boluses)} carb_events={len(state.carb_events)}",
                flush=True,
            )

        # Sleep until the next tick. Chunk so SIGINT lands quickly.
        slept = 0.0
        while slept < wall_seconds_per_tick and not stopping:
            chunk = min(0.5, wall_seconds_per_tick - slept)
            time.sleep(chunk)
            slept += chunk

    print(
        f"[emu] done. simulated {state.sim_minute / 60:.1f} hours, "
        f"{len(state.boluses)} active boluses, {len(state.carb_events)} active carbs",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
